//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTreeSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public int NodeId { get; set; }
        public string NodeName { get; set; }
        public int? ParentNodeId { get; set; }
        public bool? IsActive { get; set; }
        public System.DateTime StartDate { get; set; }

        // For tree structure
        public List<Node> Children { get; set; }

        public Node()
        {
            Children = new List<Node>();
        }
    }
}
